### ISSUE TITLE
[Tracking] All Qt UI elements that aren't themeable

### ISSUE THREAD

**Issue by luzpaz** [FreeCAD/FreeCAD#6805]
### Idea description

This ticket tracks all UI elements that aren't exposed to stylesheet theme-ability.
- [x] #16454
- [x] FreeCAD/FreeCAD#7582 
- [ ] FreeCAD/FreeCAD-themes#5 
- [x] FreeCAD/FreeCAD#8168 
- [ ] FreeCAD/FreeCAD#8250
- [x] FreeCAD/FreeCAD#8297
- [x] FreeCAD/FreeCAD#8440 
- [ ] FreeCAD/FreeCAD#9944
- [x] FreeCAD/FreeCAD#12208
- [x] https://github.com/FreeCAD/FreeCAD-addons/issues/262
- [ ] highlighter color on the tree view to see which of the fields you currently highlight ([link](https://github.com/Chrismettal/FreeCAD-Behave-dark/issues/7#issuecomment-1110815123))
- [ ] hardcoded UnitTestDialog::setRunCount ([link](https://github.com/Chrismettal/FreeCAD-Behave-dark/issues/7#issuecomment-1109931583))
- [ ] hardcoded UnitTestDialog::setFailCount ([link](https://github.com/Chrismettal/FreeCAD-Behave-dark/issues/7#issuecomment-1109931583))
- [ ] hardcoded UnitTestDialog::setErrorCount ([link](https://github.com/Chrismettal/FreeCAD-Behave-dark/issues/7#issuecomment-1109931583))
- [ ] hardcoded UnitTestDialog::setRemainCount ([link](https://github.com/Chrismettal/FreeCAD-Behave-dark/issues/7#issuecomment-1109931583))
- [ ] https://github.com/FreeCAD/FreeCAD/blob/9654786c670bbf216d062b72c03eaa1d7765bb48/src/Gui/Quarter/ContextMenu.cpp#L113-L117

### Anything else?

I was asked by chennes to open this issue and assign to him.

### Forums discussion
https://github.com/Chrismettal/FreeCAD-Behave-dark/issues/7#issuecomment-1111158376

**Comment by turn211** [comment]
1. Navigation style light icons - https://forum.freecadweb.org/viewtopic.php?f=34&t=57034&p=492685#p492685 - How can we access them to change from dark to light
2. QLineEdit#qt_spinbox_linedit - seem to be hard coded in Path Workbench 
3. Url links - About | License still has Dark Blue links - I thought this had a PR and commit by chennes
4. Spreadsheet Text - Cannot change text colour from Black - No 1 request for sure

**Comment by yorikvanhavre** [comment]
qt designer has the annoying "feature" to hardcode blue underline style for links, when using rich text in qlabels. usually one needs to go there and manually remove a styling span tag

**Comment by chennes** [comment]
The credits tab isn't created in Qt Designer, the one in there is just a placeholder. It gets replaced in the code that generates the About dialog by reading in an HTML file that's got the formatted license in it.

**Comment by yorikvanhavre** [comment]
Oh yeah sorry, i misread your previous reply

**Comment by Axeia** [comment]
I started a forum post about how aliased spreadsheet cells cannot be targeted in a stylesheet and proposed that a class 'aliased' is set on them so they can be.
https://forum.freecadweb.org/viewtopic.php?style=10&f=34&t=72294

In addition to that on Discord MisterMaker (correctly) pointed out that `QToolBar QToolButton#qt_toolbar_ext_button` behaves oddly when trying to theme it. Setting 
```QToolButton#qt_toolbar_ext_button:hover {
  background-image: url(qss:images_dark-light/more_light.svg);
}```
results in the light image appearing on top of the dark one instead of replacing it. I'm not quite sure what's going on there I'm guessing the actual source has some different element there still that we cannot seem to target with a stylesheet? I tried playing with width/background-image: none and many other things and I cannot get this bit to style properly. Googling around  it seems like this might be partially an issue with Qt and possibly partially an issue with how FreeCAD tried to remedy it? 

ps: It's the button that appears when a toolbar  overflows by either the window not having enough space or placing the toolbars in overlapping positions.

- [ ] Aliased Spreadsheet cells
- [ ] QToolBar overflow button (which seems to be a mix of `QToolButton#qt_toolbar_ext_button` and `QToolBarExtension` working together unpredictably.

**Comment by MisterMakerNL** [comment]
Link to forum topic about the ext toolbar issue:
https://forum.qt.io/topic/119988/qtoolbar-extension-button-stylesheet/2

**Comment by luzpaz** [comment]
Added:  
https://github.com/FreeCAD/FreeCAD/blob/9654786c670bbf216d062b72c03eaa1d7765bb48/src/Gui/Quarter/ContextMenu.cpp#L113-L117

**Comment by luzpaz** [comment]
Hi @adrianinsaval please feel free to update this ticket if you encounter issues in the forum you may find related. TIA!

**Comment by adrianinsaval** [comment]
ok, one is the list property editor highlight color mentioned in https://github.com/FreeCAD/FreeCAD/issues/8093

**Comment by luzpaz** [comment]
#8168

**Comment by Intuos5** [comment]
The text in the keyboard shortcuts doesn't seem to be editable from within the stylesheet: 
https://github.com/FreeCAD/FreeCAD/issues/8093#issuecomment-1403347977
The titles of the tabs in the keyboard shortcuts window or elsewhere, can those be configured? I don't recall having seen them.

(if this doesn't belong here, let me know and I'll remove the comment).

**Comment by luzpaz** [comment]
Updated OP with linked ticket numbers

**Comment by luzpaz** [comment]
Added #9944

**Comment by MisterMakerNL** [comment]
Maybe a suggestion to move the Tree view colors in the color tab to the stylesheet, so it can use the theme colors. Or just link the 2 together. 
![image](https://github.com/FreeCAD/FreeCAD/assets/29804962/08b6f77f-057b-47d9-82fa-9d1cdf90cd39)
Link them to these:
![image](https://github.com/FreeCAD/FreeCAD/assets/29804962/cb885a1e-4bd9-4bea-8adc-eec12ba0bad2)

**Comment by adrianinsaval** [comment]
Makes sense, I think it should also be possible to make those themable using the same method used for the group headers in the property view, that's not a buitl in qt functionality but it's still themable. do you think it's desirable to have those colors directly stylable?

**Comment by MisterMakerNL** [comment]
> Link to forum topic about the ext toolbar issue: https://forum.qt.io/topic/119988/qtoolbar-extension-button-stylesheet/2

I was checking if this was fixed in Qt 6 but it seems to still be broken. I am still not able to replace the icon.

![Image](https://github.com/user-attachments/assets/88c09997-aa15-469d-a66c-4a5f3c7b61d6)
